### ISSUE TITLE
As a user, I can update my account information easily, including my email and password.

### ISSUE THREAD

**Issue by Dari-Jones** [Dari-Jones/CBG_UI#10]
**User Story**
As a user, I can update my account information easily, including my email and password.

**Tasks**

- [ ] Add functionality for the user to submit their updated email or password preferences.

- [ ] Add buttons/fields to the email and password update pages

- [ ] Ensure update links are accurate and functional (located on account page)
